name: Node.js CI/CD

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test-result: ${{ steps.test.outcome }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x # Updated for Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"

      - name: Setup Deno 2.4.x
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.4.x
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run ci
        run: npm ci

      - name: Run tests
        id: test
        run: npm test
