name: CI/CD

on:
  pull_request:

jobs:
  node:
    name: Node.js (${{ matrix.node-version }})

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Tests
        run: bun run test:node

  bun:
    name: Bun (${{ matrix.bun-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install Dependencies
        run: bun install

      - name: Run Tests
        run: bun run test:bun
